version: "3.9"

services:
  standx-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./market_maker.log:/app/market_maker.log
      - ./orders.db:/app/orders.db
    restart: always
    command: [
      "--exchange", "standx",
      "--market-type", "perp",
      "--symbol", "BTC-USD",
      "--strategy", "perp_grid",
      "--grid-type", "neutral",
      "--auto-price",
      "--price-range", "1",
      "--grid-num", "40",
      "--quantity", "0.002",
      "--max-position", "2.0",
      "--duration", "3600000",
      "--interval", "14"
    ]
