version: "3.9"

services:
  standx-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # 去掉 volumes 挂载，避免文件夹冲突
    restart: always
    command: [
      "--exchange", "standx",
      "--market-type", "perp",
      "--symbol", "BTC-USD",
      "--strategy", "standard",
      "--spread", "0.10",
      "--quantity", "0.01",
      "--max-orders", "1",
      "--inventory-skew", "1.5",
      "--max-position", "0.05",
      "--target-position", "0",
      "--interval", "6",
      "--enable-rebalance",
      "--leverage", "6"
    ]
